# Generated by Django 2.2.4 on 2019-09-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salesr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('Item_Type', models.CharField(max_length=50)),
                ('Sales_Channel', models.CharField(max_length=50)),
                ('Order_Priority', models.CharField(max_length=50)),
                ('Order_Date', models.CharField(max_length=50)),
                ('Order_ID', models.CharField(max_length=50)),
                ('Ship_Date', models.CharField(max_length=50)),
                ('Units_Sold', models.IntegerField()),
                ('Unit_Price', models.FloatField()),
                ('Unit_Cost', models.FloatField()),
                ('Total_Revenue', models.FloatField()),
                ('Total_Cost', models.FloatField()),
                ('Total_Profit', models.FloatField()),
            ],
        ),
    ]
