# Generated by Django 2.2.4 on 2019-09-12 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Salesr',
            new_name='CSVdata',
        ),
    ]
